name: Output information metadata
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-22.04
        steps:
            - name: output GitHub context
              run: echo "${{ toJson(github) }}"